spring:
  datasource:
    dynamic:
      primary: rsmanage  # 将主数据源名称改为 rsmanage
      datasource:
        rsmanage:  # 数据源配置节点也改为 rsmanage
          type: com.zaxxer.hikari.HikariDataSource
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: root
          password: root
          url: jdbc:mysql://rsmanage-mysql:3306/rsmanage?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowMultiQueries=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true
