version: '3'
services:
  rsmanage-mysql:
    build:
      context: ./db
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: root1234
    restart: always
    container_name: rsmanage-mysql
    image: rsmanage-mysql
    ports:
      - 33306:3306
    networks:
      - spring_cloud_default

  rsmanage-redis:
    image: redis:latest
    ports:
      - 36379:6379
    restart: always
    container_name: rsmanage-redis
    hostname: rsmanage-redis
    networks:
      - spring_cloud_default

  rsmanage-register:
    build:
      context: ./rsmanage-register
    restart: always
    ports:
      - 8848:8848
      - 9848:9848
    container_name: rsmanage-register
    hostname: rsmanage-register
    image: rsmanage-register
    networks:
      - spring_cloud_default

  rsmanage-gateway:
    build:
      context: ./rsmanage-gateway
    restart: always
    ports:
      - 9999:9999
    container_name: rsmanage-gateway
    hostname: rsmanage-gateway
    image: rsmanage-gateway
    networks:
      - spring_cloud_default

  rsmanage-auth:
    build:
      context: ./rsmanage-auth
    restart: always
    container_name: rsmanage-auth
    hostname: rsmanage-auth
    image: rsmanage-auth
    networks:
      - spring_cloud_default

  rsmanage-upms:
    build:
      context: ./rsmanage-upms/rsmanage-upms-biz
    restart: always
    container_name: rsmanage-upms
    hostname: rsmanage-upms
    image: rsmanage-upms
    networks:
      - spring_cloud_default

  rsmanage-customer:
    build:
      context: ./rsmanage-customer/rsmanage-customer-biz
    restart: always
    container_name: rsmanage-customer
    hostname: rsmanage-customer
    image: rsmanage-customer
    networks:
      - spring_cloud_default

  rsmanage-monitor:
    build:
      context: ./rsmanage-visual/rsmanage-monitor
    restart: always
    ports:
      - 5001:5001
    container_name: rsmanage-monitor
    hostname: rsmanage-monitor
    image: rsmanage-monitor
    networks:
      - spring_cloud_default

  rsmanage-codegen:
    build:
      context: ./rsmanage-visual/rsmanage-codegen
    restart: always
    container_name: rsmanage-codegen
    hostname: rsmanage-codegen
    image: rsmanage-codegen
    networks:
      - spring_cloud_default

  rsmanage-quartz:
    build:
      context: ./rsmanage-visual/rsmanage-quartz
    restart: always
    image: rsmanage-quartz
    container_name: rsmanage-quartz
    networks:
      - spring_cloud_default

networks:
  spring_cloud_default:
    name:  spring_cloud_default
    driver: bridge
