name: 同步代码

on:
  push:
    branches: [ master,dev ]
  pull_request:
    branches: [ master,dev ]

jobs:
  gitcode:
    runs-on: ubuntu-latest
    steps:
      - uses: wearerequired/git-mirror-action@master #同步至 gitcode
        env:
          SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        with:
          source-repo: "git@github.com:rsmanage-mesh/rsmanage-ui.git"
          destination-repo: "git@gitcode.com:rsmanage-mesh/rsmanage-ui.git"
  gitlink:
    runs-on: ubuntu-latest
    steps:
      - uses: wearerequired/git-mirror-action@master #同步至 gitlink
        env:
          SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        with:
          source-repo: "git@github.com:rsmanage-mesh/rsmanage-ui.git"
          destination-repo: "git@code.gitlink.org.cn:lengleng/rsmanage-ui.git"
  gitee:
    runs-on: ubuntu-latest
    container:
      image: "centos:8"
    steps:
      - uses: wearerequired/git-mirror-action@master #同步至 gitee
        env:
          SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        with:
          source-repo: "git@github.com:rsmanage-mesh/rsmanage-ui.git"
          destination-repo: "git@gitee.com:log4j/rsmanage-ui.git"
